Repository DEFRA/waste-carriers-back-office, pull requests merged in 2019-10, with the labels that each got.

#376 Update dashboard search design
  app/controllers/dashboards_controller.rb
  app/services/search_service.rb
  app/services/transient_registration_search_service.rb
  app/services/waste_carriers_engine/base_service.rb
  app/views/dashboards/index.html.erb
  config/locales/dashboard.en.yml
  config/locales/en.yml
  spec/services/search_service_spec.rb
  spec/services/transient_registration_search_service_spec.rb
Labels: enhancement

#377 Add actions panel to dashboard
  app/assets/stylesheets/partials/_dashboards.scss
  app/views/dashboards/index.html.erb
  config/locales/dashboard.en.yml
Labels: enhancement

#378 Update dashboard search result design
  app/assets/stylesheets/partials/_dashboards.scss
  app/assets/stylesheets/partials/_tags.scss
  app/controllers/dashboards_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/dashboards_helper.rb
  app/views/dashboards/index.html.erb
  config/locales/dashboard.en.yml
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/dashboards_helper_spec.rb
Labels: enhancement

#381 Add visually hidden link text to search result actions
  app/views/dashboards/index.html.erb
  config/locales/dashboard.en.yml
Labels: enhancement

#382 Include registrations in dashboard search
  Gemfile.lock
  app/helpers/action_links_helper.rb
  app/services/search_service.rb
  app/views/dashboards/index.html.erb
  spec/helpers/action_links_helper_spec.rb
  spec/services/search_service_spec.rb
Labels: enhancement

#384 Determine which tags to display in search results
  app/assets/stylesheets/partials/_tags.scss
  app/helpers/dashboards_helper.rb
  app/services/status_tag_service.rb
  app/views/dashboards/index.html.erb
  config/locales/dashboard.en.yml
  spec/services/status_tag_service_spec.rb
Labels: enhancement

#386 Display 'transfer' link on registration results
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#391 Add 'inactive' tag text
  app/assets/stylesheets/partials/_tags.scss
  config/locales/dashboard.en.yml
Labels: bug

#389 Improve contrast on 'expired' tag
  app/assets/stylesheets/partials/_tags.scss
Labels: bug

#393 Display 'renew' action on renewable reg results
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#394 Display 'new registration' for pending new regs
  app/helpers/dashboards_helper.rb
  config/locales/dashboard.en.yml
  spec/helpers/dashboards_helper_spec.rb
Labels: enhancement

#387 Display correct date on search results
  app/helpers/dashboards_helper.rb
  app/views/dashboards/index.html.erb
  config/initializers/time_formats.rb
  config/locales/dashboard.en.yml
  spec/helpers/dashboards_helper_spec.rb
Labels: enhancement

#404 Apply role permissions to dashboard links
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  spec/helpers/action_links_helper_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#400 Move action link paths to helper
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: housekeeping

#402 Add payment link for new registrations
  Gemfile.lock
  app/helpers/action_links_helper.rb
  spec/factories/registration.rb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#390 Display correct number of results on dashboard
  app/controllers/dashboards_controller.rb
  app/services/search_service.rb
  app/views/dashboards/index.html.erb
  spec/services/search_service_spec.rb
Labels: bug

#405 Display payment tag for new registrations
  app/services/status_tag_service.rb
  spec/services/status_tag_service_spec.rb
Labels: enhancement

#399 Display convictions tag for new registrations
  Gemfile.lock
  app/services/status_tag_service.rb
  spec/services/status_tag_service_spec.rb
Labels: enhancement

#408 Update title of registration view
  config/locales/transient_registrations.en.yml
Labels: enhancement

#407 Add call out box for registration info
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_registrations.scss
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#412 Add actions box on Registration details page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_dashboards.scss
  app/assets/stylesheets/partials/_registrations.scss
  app/assets/stylesheets/partials/_wcr-objects.scss
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#409 Add Contact and Business details side to side panels
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_registrations.scss
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#406 Make dashboard CSS class names less generic
  app/assets/stylesheets/partials/_dashboards.scss
  app/views/dashboards/index.html.erb
Labels: bug

#417 Add prefix to CSS wcr specific objects
  app/assets/stylesheets/partials/_wcr-objects.scss
  app/views/dashboards/index.html.erb
  app/views/transient_registrations/show.html.erb
Labels: bug

#411 Update conviction section in view details
  app/views/transient_registrations/show.html.erb
Labels: enhancement
