Repository DEFRA/waste-carriers-back-office, pull requests merged in 2019-11, with the labels that each got.

#421 Show correct messag when finance information is missing
  app/views/transient_registrations/show.html.erb
Labels: enhancement

#420 Move link down in conviction section
  app/views/transient_registrations/show.html.erb
Labels: enhancement

#419 Match details top page with wireframes
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#418 Remove convictions link from details page actions
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#422 Fix indentation, unclosed div and link text
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#423 Add p tag around finance details link
  app/views/transient_registrations/show.html.erb
Labels: enhancement

#424 Accessibility - Use th in tables
  app/views/transient_registrations/show.html.erb
Labels: enhancement

#425 Return empty string if no date available
  app/helpers/dashboards_helper.rb
  spec/helpers/dashboards_helper_spec.rb
Labels: bug

#426 Remove registration information section
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: enhancement

#428 Fix typo and add missing translation
  app/views/transient_registrations/show.html.erb
  config/locales/transient_registrations.en.yml
Labels: bug

#431 Remove conviction details link in dashboard
  app/views/dashboards/index.html.erb
Labels: enhancement

#432 Use RenewingRegistration instead of TransientRegistration
  Gemfile.lock
  app/controllers/admin_forms_controller.rb
  app/controllers/convictions_controller.rb
  app/controllers/convictions_dashboards_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/transient_registrations_controller.rb
  app/controllers/worldpay_escapes_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/dashboards_helper.rb
  app/models/ability.rb
  app/presenters/waste_carriers_engine/registration_details_presenter.rb
  app/services/registration_transfer_service.rb
  app/services/search_service.rb
  lib/tasks/addresses.rake
  lib/tasks/stuck.rake
  spec/factories/forms/conviction_reason_form.rb
  spec/factories/forms/payment_form.rb
  spec/factories/renewing_registration.rb
  spec/forms/conviction_reason_form_spec.rb
  spec/forms/payment_form_spec.rb
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/convictions_helper_spec.rb
  spec/helpers/dashboards_helper_spec.rb
  spec/helpers/payments_helper_spec.rb
  spec/helpers/transient_registrations_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/assisted_digital_forms_spec.rb
  spec/requests/cash_payment_forms_spec.rb
  spec/requests/cheque_payment_forms_spec.rb
  spec/requests/conviction_approval_forms_spec.rb
  spec/requests/conviction_rejection_forms_spec.rb
  spec/requests/convictions_dashboards_spec.rb
  spec/requests/convictions_spec.rb
  spec/requests/dashboards_spec.rb
  spec/requests/payments_spec.rb
  spec/requests/postal_order_payment_forms_spec.rb
  spec/requests/transfer_payment_forms_spec.rb
  spec/requests/transient_registrations_spec.rb
  spec/requests/worldpay_escapes_spec.rb
  spec/requests/worldpay_missed_payment_forms_spec.rb
  spec/services/registration_transfer_service_spec.rb
  spec/services/search_service_spec.rb
  spec/services/status_tag_service_spec.rb
Labels: enhancement

#438 Remove dupe BaseService
  app/services/waste_carriers_engine/base_service.rb
Labels: housekeeping

#444 Details page: TransientRegistration to RenewingRegistration
  app/controllers/admin_forms_controller.rb
  app/controllers/renewing_registrations_controller.rb
  app/controllers/worldpay_escapes_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/renewing_registrations_helper.rb
  app/views/cash_payment_forms/new.html.erb
  app/views/cheque_payment_forms/new.html.erb
  app/views/convictions/index.html.erb
  app/views/payments/new.html.erb
  app/views/postal_order_payment_forms/new.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/transfer_payment_forms/new.html.erb
  app/views/worldpay_missed_payment_forms/new.html.erb
  config/locales/renewing_registrations.en.yml
  config/routes.rb
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/renewing_registrations_helper_spec.rb
  spec/requests/cash_payment_forms_spec.rb
  spec/requests/cheque_payment_forms_spec.rb
  spec/requests/convictions_dashboards_spec.rb
  spec/requests/dashboards_spec.rb
  spec/requests/postal_order_payment_forms_spec.rb
  spec/requests/renewing_registrations_spec.rb
  spec/requests/transfer_payment_forms_spec.rb
  spec/requests/worldpay_escapes_spec.rb
  spec/requests/worldpay_missed_payment_forms_spec.rb
Labels: enhancement, housekeeping

#445 Add registration details page
  app/controllers/registrations_controller.rb
  app/helpers/action_links_helper.rb
  app/presenters/registration_presenter.rb
  app/presenters/waste_carriers_engine/registration_details_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_in_progress_panel.html.erb
  app/views/shared/registrations/_pending_conviction_panel.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
  config/locales/registrations.en.yml
  config/routes.rb
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/registration_presenter_spec.rb
  spec/requests/registrations_spec.rb
Labels: enhancement

#447 Add Unknown status to conviction cheks view details
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
Labels: enhancement

#448 Remove conviction links
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
Labels: enhancement

#439 Refactor UserMigrationService to inherit from BaseService
  app/controllers/user_migrations_controller.rb
  app/services/user_migration_service.rb
  spec/services/user_migration_service_spec.rb
Labels: housekeeping

#440 Refactor RegistrationTransferService to inherit from BaseService
  app/forms/registration_transfer_form.rb
  app/services/registration_transfer_service.rb
  spec/forms/registration_transfer_form_spec.rb
  spec/services/registration_transfer_service_spec.rb
Labels: housekeeping

#449 Remove expire information for Lower tier
  app/views/registrations/show.html.erb
Labels: enhancement

#452 Fix: xsmall -> small
  app/views/registrations/show.html.erb
Labels: bug

#453 Create presenter for RenewingRegistration details page
  app/controllers/renewing_registrations_controller.rb
  app/helpers/renewing_registrations_helper.rb
  app/presenters/base_registration_presenter.rb
  app/presenters/registration_presenter.rb
  app/presenters/renewing_registration_presenter.rb
  app/views/renewing_registrations/show.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
  spec/helpers/renewing_registrations_helper_spec.rb
  spec/presenters/base_registration_presenter_spec.rb
  spec/presenters/registration_presenter_spec.rb
  spec/presenters/renewing_registration_presenter_spec.rb
Labels: housekeeping

#455 Convictions message for lower tier registrations
  app/presenters/base_registration_presenter.rb
  app/presenters/registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
  spec/presenters/base_registration_presenter_spec.rb
Labels: enhancement

#456 Finance message on lower tier registration finance section
  app/presenters/base_registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_finance_details.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
  spec/presenters/base_registration_presenter_spec.rb
Labels: enhancement

#457 Add continue application link to details page
  app/presenters/base_registration_presenter.rb
  app/presenters/renewing_registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
  spec/presenters/base_registration_presenter_spec.rb
  spec/presenters/renewing_registration_presenter_spec.rb
Labels: enhancement, housekeeping

#458 Add renew link to actions panel in details page
  app/helpers/action_links_helper.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/shared/registrations.en.yml
Labels: enhancement

#459 Display 'expired' instead of 'expires' if expired
  app/presenters/base_registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
  spec/presenters/base_registration_presenter_spec.rb
  spec/presenters/registration_presenter_spec.rb
  spec/presenters/renewing_registration_presenter_spec.rb
Labels: bug

#464 Move company details panel to partial
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_company_details_panel.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
Labels: housekeeping

#463 Add expired panel to view details pages
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_expired_panel.html.erb
  config/locales/shared/registrations.en.yml
Labels: enhancement

#466 Move rejected message status into partial
  app/presenters/registration_presenter.rb
  app/presenters/renewing_registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_rejected_conviction_checks_details.html.erb
  spec/presenters/registration_presenter_spec.rb
  spec/presenters/renewing_registration_presenter_spec.rb
Labels: housekeeping

#462 Add all action links to details page
  app/assets/stylesheets/partials/_wcr-objects.scss
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/presenters/registration_presenter.rb
  app/presenters/renewing_registration_presenter.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_finance_details.html.erb
  config/locales/shared/registrations.en.yml
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/registration_presenter_spec.rb
  spec/presenters/renewing_registration_presenter_spec.rb
Labels: enhancement

#465 Move shared panels to partials on details page views
  app/presenters/registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_contact_and_business_details_panels.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
Labels: housekeeping

#468 Move last sections to partials in details page
  app/presenters/base_registration_presenter.rb
  app/views/registrations/show.html.erb
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_main_people_details.html.erb
  app/views/shared/registrations/_pending_convictions_panel.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
  config/locales/registrations.en.yml
  config/locales/renewing_registrations.en.yml
  config/locales/shared/registrations.en.yml
  spec/presenters/base_registration_presenter_spec.rb
Labels: housekeeping

#467 Refactor ability specs
  spec/models/ability_spec.rb
  spec/models/user_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/agency_super_examples.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_super_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: housekeeping

#469 Details page - Fixes
  app/helpers/action_links_helper.rb
  app/presenters/registration_presenter.rb
  app/views/dashboards/index.html.erb
  app/views/registrations/show.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/shared/registrations.en.yml
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/base_registration_presenter_spec.rb
  spec/presenters/registration_presenter_spec.rb
Labels: enhancement

#470 Make 'revert to payment summary' button display
  app/models/ability.rb
Labels: bug

#472 Use classes instead of objects in ability specs
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/agency_super_examples.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_super_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: housekeeping

#471 Update ActionLinksHelper to use cleaner methods
  app/helpers/action_links_helper.rb
Labels: housekeeping

#473 Fix backend links
  app/helpers/action_links_helper.rb
  app/presenters/registration_presenter.rb
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/registration_presenter_spec.rb
Labels: bug

#474 Changes to finance details
  app/presenters/base_registration_presenter.rb
  app/views/shared/registrations/_finance_details.html.erb
  config/locales/shared/registrations.en.yml
  spec/presenters/base_registration_presenter_spec.rb
Labels: enhancement

#475 Fix messages to match wireframe
  config/locales/renewing_registrations.en.yml
Labels: enhancement

#476 Redirects after a renewing is confirmed
  app/controllers/registrations_controller.rb
  app/controllers/renewing_registrations_controller.rb
  config/mongoid.yml
  spec/requests/renewing_registrations_spec.rb
Labels: bug, enhancement

#478 Remove all links to old backend
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_expired_panel.html.erb
  app/views/shared/registrations/_finance_details.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: bug
