Repository DEFRA/waste-carriers-back-office, pull requests merged in 2019-12, with the labels that each got.

#479 Add classes for reports exports
  .env.example
  .travis.yml
  Gemfile
  Gemfile.lock
  app/models/reports/base_serializer.rb
  app/models/reports/epr_serializer.rb
  app/services/concerns/can_load_file_to_aws.rb
  app/services/reports/epr_export_service.rb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  config/schedule.rb
  lib/close_airbrake.rb
  lib/tasks/reports.rake
  spec/lib/tasks/reports_spec.rb
  spec/models/reports/base_serializer_spec.rb
  spec/models/reports/epr_serializer_spec.rb
  spec/schedule_spec.rb
  spec/services/reports/epr_export_service_spec.rb
  spec/support/rake_env.rb
  spec/support/shared_examples/rake.rb
Labels: enhancement

#483 Update conviction dashboard to include registrations
  Gemfile.lock
  app/controllers/convictions_dashboards_controller.rb
  app/views/shared/_convictions_dashboard_results.html.erb
  spec/factories/meta_data.rb
  spec/factories/registration.rb
  spec/requests/convictions_dashboards_spec.rb
Labels: enhancement

#482 Redirect to registration details after transfering
  app/helpers/registration_transfers_helper.rb
  app/views/registration_transfers/success.html.erb
  spec/helpers/registration_transfers_helper_spec.rb
Labels: enhancement

#485 Deal with new frontend regs on possible matches list
  Gemfile.lock
  app/controllers/convictions_dashboards_controller.rb
  spec/requests/convictions_dashboards_spec.rb
Labels: enhancement

#487 Remove mention of 'renewals' from convictions dashboard
  config/locales/convictions_dashboards.en.yml
Labels: bug

#486 Update conviction details page to work with new registrations
  app/controllers/convictions_controller.rb
  app/helpers/convictions_helper.rb
  app/presenters/base_conviction_presenter.rb
  app/presenters/registration_conviction_presenter.rb
  app/presenters/renewing_registration_conviction_presenter.rb
  app/views/convictions/index.html.erb
  config/locales/convictions.en.yml
  config/routes.rb
  spec/helpers/convictions_helper_spec.rb
  spec/presenters/base_conviction_presenter_spec.rb
  spec/presenters/registration_conviction_presenter_spec.rb
  spec/presenters/renewing_registration_conviction_presenter_spec.rb
  spec/requests/convictions_spec.rb
Labels: enhancement

#488 Link to reg conviction details pages from dashboard
  app/helpers/convictions_dashboards_helper.rb
  app/views/shared/_convictions_dashboard_results.html.erb
  spec/helpers/convictions_dashboards_helper_spec.rb
  spec/requests/convictions_dashboards_spec.rb
Labels: enhancement

#489 Move conviction details logic from helper to presenters
  app/helpers/convictions_helper.rb
  app/presenters/base_conviction_presenter.rb
  app/views/convictions/index.html.erb
  app/views/shared/_conviction_search_result.html.erb
  config/initializers/time_formats.rb
  config/locales/convictions.en.yml
  spec/helpers/convictions_helper_spec.rb
  spec/presenters/base_conviction_presenter_spec.rb
Labels: housekeeping

#491 Make 'begin checks' action work for registration convictions
  app/controllers/convictions_controller.rb
  app/presenters/registration_conviction_presenter.rb
  app/presenters/renewing_registration_conviction_presenter.rb
  app/views/convictions/index.html.erb
  config/routes.rb
  spec/presenters/registration_conviction_presenter_spec.rb
  spec/presenters/renewing_registration_conviction_presenter_spec.rb
  spec/requests/convictions_spec.rb
Labels: enhancement

#494 Add visually hidden link text to convictions dashboard
  app/views/shared/_convictions_dashboard_results.html.erb
  config/locales/convictions_dashboards.en.yml
Labels: bug

#495 Update registration's conviction status when approving check
  app/controllers/registration_conviction_approval_forms_controller.rb
  spec/requests/registration_conviction_approval_forms_spec.rb
Labels: enhancement

#496 Change reg conviction workflow status on reject
  app/controllers/registration_conviction_rejection_forms_controller.rb
  spec/requests/registration_conviction_rejection_forms_spec.rb
Labels: enhancement

#497 Implement revocal or refusal of reg after conviction check
  Gemfile.lock
  app/controllers/conviction_rejection_forms_controller.rb
  app/controllers/registration_conviction_rejection_forms_controller.rb
  spec/factories/registration.rb
  spec/factories/renewing_registration.rb
  spec/requests/conviction_rejection_forms_spec.rb
  spec/requests/registration_conviction_rejection_forms_spec.rb
Labels: enhancement

#498 Don't display 'pending checks' message after rejection
  app/views/registrations/show.html.erb
Labels: bug

#504 Flash messages style
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_flash-messages.scss
Labels: enhancement

#506 Remove unused code
  app/presenters/registration_presenter.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  spec/presenters/registration_presenter_spec.rb
Labels: enhancement

#505 Add link to order copy cards journey
  app/helpers/action_links_helper.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/routes.rb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#509 Add formatted date for order copy cards mailer
  config/initializers/time_formats.rb
Labels: enhancement

#510 Fix 'continue as AD' button
  app/views/renewing_registrations/show.html.erb
  app/views/shared/registrations/_in_progress_panel.html.erb
  spec/requests/renewing_registrations_spec.rb
Labels: bug

#512 Fix broken back link on successful reg transfer
  app/controllers/registration_transfers_controller.rb
  app/views/registration_transfers/success.html.erb
  spec/requests/registration_transfers_spec.rb
Labels: bug

#513 Update user list
  app/helpers/users_helper.rb
  app/models/ability.rb
  app/models/user.rb
  app/views/users/index.html.erb
  config/locales/users.en.yml
  spec/helpers/users_helper_spec.rb
  spec/models/user_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/agency_super_examples.rb
  spec/support/shared_examples/abilities/below_agency_super_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: enhancement

#516 Fix flash messages colours
  app/assets/stylesheets/partials/_flash-messages.scss
Labels: bug

#519 Implement EPR export
  app/models/reports/base_serializer.rb
  app/models/reports/epr_serializer.rb
  app/presenters/reports/registration_epr_presenter.rb
  config/initializers/time_formats.rb
  spec/models/reports/base_serializer_spec.rb
  spec/models/reports/epr_serializer_spec.rb
  spec/presenters/reports/registration_epr_presenter_spec.rb
Labels: enhancement

#521 Add main service for boxi export job
  .env.example
  .travis.yml
  Gemfile
  Gemfile.lock
  app/services/reports/boxi_export_service.rb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  lib/tasks/reports.rake
  spec/services/reports/boxi_export_service_spec.rb
Labels: enhancement

#522 Naming fixes to exports code structure
  app/models/reports/base_serializer.rb
  app/models/reports/epr_serializer.rb
  spec/models/reports/base_serializer_spec.rb
Labels: enhancement

#524 Use correct bucket name for boxi
  config/initializers/defra_ruby_aws.rb
Labels: bug

#525 Add base boxi report generator service
  app/models/reports/boxi/addresses_serializer.rb
  app/models/reports/boxi/base_serializer.rb
  app/services/reports/boxi_export_service.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
  spec/services/reports/boxi_export_service_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#527 Add key people file creation on Boxi export
  app/models/reports/boxi/addresses_serializer.rb
  app/models/reports/boxi/key_people_serializer.rb
  app/presenters/reports/boxi/key_person_presenter.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/key_people_serializer_spec.rb
  spec/presenters/reports/boxi/key_person_presenter_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#528 Implement creation of order_items file for Boxi
  app/models/reports/boxi/order_items_serializer.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/factories/finance_details.rb
  spec/factories/order.rb
  spec/factories/payment.rb
  spec/factories/registration.rb
  spec/models/reports/boxi/order_items_serializer_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#529 Implement Boxi Orders csv file creation
  app/models/reports/boxi/orders_serializer.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/orders_serializer_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#530 Add code to generate payments boxi export
  app/models/reports/boxi/payments_serializer.rb
  app/presenters/reports/boxi/payment_presenter.rb
  app/services/reports/generate_boxi_files_service.rb
  config/initializers/time_formats.rb
  spec/models/reports/boxi/payments_serializer_spec.rb
  spec/presenters/reports/boxi/payment_presenter_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#531 Implement generation of registration csv for Boxi
  app/models/reports/boxi/registrations_serializer.rb
  app/presenters/reports/boxi/registration_presenter.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/registrations_serializer_spec.rb
  spec/presenters/reports/boxi/registration_presenter_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#532 Implement code for sign_offs csv Boxi file
  app/models/reports/boxi/sign_offs_serializer.rb
  app/presenters/reports/boxi/sign_off_presenter.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/sign_offs_serializer_spec.rb
  spec/presenters/reports/boxi/sign_off_presenter_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: enhancement

#537 Fix issue when missing finance details
  app/presenters/reports/boxi/key_person_presenter.rb
  app/presenters/reports/boxi/registration_presenter.rb
Labels: bug

#536 Add expire registrations job
  .env.example
  app/services/expired_registrations_service.rb
  config/schedule.rb
  lib/tasks/expire_registration.rake
  spec/schedule_spec.rb
  spec/services/expired_registrations_service_spec.rb
Labels: enhancement

#538 Fix bug on finance details heading lower tier old reg
  app/presenters/base_registration_presenter.rb
  app/views/shared/registrations/_finance_details.html.erb
  spec/presenters/base_registration_presenter_spec.rb
Labels: bug

#540 Add cease or revoke links
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/dashboard.en.yml
  config/locales/shared/registrations.en.yml
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#543 Add flash messages and style for ceased or revoked
  app/assets/stylesheets/partials/_buttons.scss
  app/views/dashboards/index.html.erb
Labels: enhancement

#545 Rename payments controller to transient_payments
  app/controllers/transient_payments_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/transient_payments_helper.rb
  app/views/transient_payments/new.html.erb
  config/locales/transient_payments.en.yml
  config/routes.rb
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/transient_payments_helper_spec.rb
  spec/requests/transfer_payment_forms_spec.rb
  spec/requests/transient_payments_spec.rb
Labels: enhancement
