Repository DEFRA/waste-carriers-back-office, pull requests merged in 2020-04, with the labels that each got.

#800 Add api endpoint for acceptance tests
  app/controllers/api/registrations_controller.rb
  app/controllers/api/renewals_controller.rb
  config/feature_toggles.yml
  config/routes.rb
  spec/requests/api/registrations_spec.rb
  spec/requests/api/renewals_spec.rb
Labels: enhancement

#805 Enable Edit registration feature
  app/models/ability.rb
  config/feature_toggles.yml
  spec/support/shared_examples/abilities/agency_examples.rb
Labels: enhancement

#807 Fix json dependency security issue
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#811 Add expired registrations in grace window to EPR
  app/models/reports/epr_serializer.rb
  app/presenters/reports/registration_epr_presenter.rb
  spec/factories/meta_data.rb
  spec/factories/registration.rb
  spec/models/reports/epr_serializer_spec.rb
  spec/presenters/reports/registration_epr_presenter_spec.rb
Labels: enhancement

#812 Add base service to fetch expiring registrations
  app/services/renewal_reminder_service_base.rb
  spec/services/renewal_reminder_service_base_spec.rb
Labels: enhancement

#815 Don't try to display account email if none exists
  app/views/shared/registrations/_company_details_panel.html.erb
Labels: bug

#814 Add code to send first renewal reminder letter via rake task
  app/mailers/renewal_reminder_mailer.rb
  app/services/first_renewal_reminder_service.rb
  app/views/renewal_reminder_mailer/first_reminder_email.html.erb
  config/application.rb
  config/locales/mailers/renewal_reminder_mailer/first_reminder_email.en.yml
  lib/tasks/email.rake
  spec/mailers/renewal_reminder_mailer_spec.rb
Labels: enhancement

#816 Fix error on configuration application
  app/services/first_renewal_reminder_service.rb
Labels: bug

#817 Schedule first email reminder task
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#820 Add feature toggle to email reminders
  config/feature_toggles.yml
  lib/tasks/email.rake
Labels: enhancement

#822 Generate second renewal reminder email
  app/mailers/renewal_reminder_mailer.rb
  app/services/second_renewal_reminder_service.rb
  app/views/renewal_reminder_mailer/second_reminder_email.html.erb
  config/application.rb
  config/locales/mailers/renewal_reminder_mailer/second_reminder_email.en.yml
  lib/tasks/email.rake
  spec/mailers/renewal_reminder_mailer_spec.rb
Labels: enhancement

#824 Add API endpoint to seed data using JSON seeds
  app/controllers/api/registrations_controller.rb
  app/services/api/load_seeded_data_service.rb
  config/routes.rb
  spec/requests/api/registrations_spec.rb
  spec/services/api/load_seeded_data_service_spec.rb
  spec/support/fixtures/registration_seed.json
Labels: enhancement

#825 Fix SonarCloud code coverage reporting
  Gemfile
  Gemfile.lock
Labels: bug

#827 Use multiple rubocop formats in Travis build
  .travis.yml
Labels: housekeeping

#830 Change seeds api to set expires_on
  app/services/api/load_seeded_data_service.rb
  spec/requests/api/registrations_spec.rb
  spec/services/api/load_seeded_data_service_spec.rb
Labels: enhancement

#832 Add configs for defra ruby address gem
  config/initializers/waste_carriers_engine.rb
Labels: enhancement

#836 Use env variable for AD email
  app/services/renewal_reminder_service_base.rb
  spec/services/renewal_reminder_service_base_spec.rb
Labels: bug
