Repository DEFRA/waste-carriers-back-office, pull requests merged in 2020-02, with the labels that each got.

#640 Boxi - Unique UID for orders
  app/models/reports/boxi/order_items_serializer.rb
  app/models/reports/boxi/orders_serializer.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/order_items_serializer_spec.rb
  spec/models/reports/boxi/orders_serializer_spec.rb
Labels: bug

#641 Fix sanitizer method
  app/models/reports/boxi/base_serializer.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
Labels: bug

#645 Write offs - fixes
  app/forms/write_off_form.rb
  app/models/ability.rb
  app/views/devise/invitations/new.html.erb
  app/views/user_roles/new.html.erb
  app/views/write_off_forms/new.html.erb
  config/locales/write_off_forms.en.yml
  spec/requests/write_off_forms_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
Labels: bug

#642 View registration certificate in back office
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/certificates_controller.rb
  app/controllers/concerns/can_render_pdf.rb
  config/routes.rb
  spec/factories/meta_data.rb
  spec/requests/certificates_spec.rb
Labels: enhancement

#648 Delete one off address fix rake task
  lib/tasks/addresses.rake
Labels: housekeeping

#649 Remove unused passenger rake tasks
  lib/tasks/passenger.rake
Labels: housekeeping

#652 Add renewing after create to write off
  app/controllers/write_off_forms_controller.rb
  spec/requests/write_off_forms_spec.rb
Labels: enhancement

#647 Switch airbrake mgmt to defra-ruby-alert
  Gemfile
  Gemfile.lock
  config/initializers/airbrake.rb
  config/initializers/waste_carriers_engine.rb
  lib/close_airbrake.rb
  lib/tasks/expire_registration.rake
  lib/tasks/reports.rake
Labels: housekeeping

#655 Move title and validations to two-thirds column
  app/views/write_off_forms/new.html.erb
Labels: bug

#646 Display 'view certificate' actions link
  app/helpers/action_links_helper.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/shared/registrations.en.yml
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#653 Fix finance role permissions
  app/models/ability.rb
  spec/models/ability_spec.rb
  spec/requests/cash_payment_forms_spec.rb
  spec/requests/cheque_payment_forms_spec.rb
  spec/requests/postal_order_payment_forms_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_finance_super_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: bug

#656 Clean up action link helpers
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: housekeeping

#657 Add edit ability
  app/models/ability.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
Labels: enhancement

#654 Log error from completion service without parsing it
  app/controllers/admin_forms_controller.rb
  app/controllers/concerns/can_renew_if_possible.rb
Labels: enhancement

#661 Update details link text
  config/locales/dashboard.en.yml
Labels: enhancement

#660 Add edit link to registration details page
  app/helpers/action_links_helper.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#662 Remove expired panel from renewing registration details page
  app/views/renewing_registrations/show.html.erb
Labels: bug

#644 Finance - Charge adjust
  app/controllers/charge_adjust_start_forms_controller.rb
  app/controllers/negative_charge_adjust_forms_controller.rb
  app/controllers/positive_charge_adjust_forms_controller.rb
  app/forms/charge_adjust_start_form.rb
  app/forms/concerns/can_convert_string_to_pence.rb
  app/forms/concerns/can_have_charge_adjust_attributes.rb
  app/forms/negative_charge_adjust_form.rb
  app/forms/positive_charge_adjust_form.rb
  app/models/ability.rb
  app/services/process_charge_adjust_service.rb
  app/views/charge_adjust_start_forms/new.html.erb
  app/views/negative_charge_adjust_forms/new.html.erb
  app/views/positive_charge_adjust_forms/new.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  config/application.rb
  config/locales/charge_adjust_start_forms.en.yml
  config/locales/negative_charge_adjust_forms.en.yml
  config/locales/positive_charge_adjust_forms.en.yml
  config/routes.rb
  spec/forms/charge_adjust_start_form_spec.rb
  spec/forms/negative_charge_adjust_form_spec.rb
  spec/forms/positive_charge_adjust_form_spec.rb
  spec/requests/charge_adjust_start_forms_spec.rb
  spec/requests/negative_charge_adjust_forms_spec.rb
  spec/requests/positive_charge_adjust_forms_spec.rb
  spec/services/process_charge_adjust_service_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/developer_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: enhancement

#665 Add styles for edit feature
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_edit.scss
Labels: enhancement

#664 Finance - Add ability to revert a payment
  app/controllers/refunds_controller.rb
  app/controllers/resource_forms_controller.rb
  app/controllers/reversal_forms_controller.rb
  app/forms/reversal_form.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/presenters/payment_presenter.rb
  app/services/process_reversal_service.rb
  app/views/reversal_forms/index.html.erb
  app/views/reversal_forms/new.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  config/locales/reversal_forms.en.yml
  config/routes.rb
  spec/factories/payment.rb
  spec/forms/reversal_form_spec.rb
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/payment_presenter_spec.rb
  spec/requests/refunds_spec.rb
  spec/requests/reversal_forms_spec.rb
  spec/services/process_reversal_service_spec.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
Labels: enhancement

#666 Add view payments ability
  app/controllers/payments_controller.rb
  app/controllers/reversal_forms_controller.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/views/shared/registrations/_finance_action_links.html.erb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/payments_spec.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
Labels: enhancement

#668 Fix id of fieldset for validation link
  app/views/write_off_forms/new.html.erb
Labels: bug

#672 Fix back buttons
  app/views/cash_payment_forms/new.html.erb
  app/views/cheque_payment_forms/new.html.erb
  app/views/postal_order_payment_forms/new.html.erb
  app/views/reversal_forms/new.html.erb
  app/views/worldpay_missed_payment_forms/new.html.erb
Labels: bug

#674 Fix bug on worlpday missed payment for registrations
  app/controllers/worldpay_missed_payment_forms_controller.rb
  spec/requests/worldpay_missed_payment_forms_spec.rb
Labels: bug

#676 Payments - Move validation box above H1
  app/views/bank_transfer_payment_forms/new.html.erb
  app/views/cash_payment_forms/new.html.erb
  app/views/cheque_payment_forms/new.html.erb
  app/views/postal_order_payment_forms/new.html.erb
  app/views/shared/_payment_form.html.erb
  app/views/worldpay_missed_payment_forms/new.html.erb
Labels: bug

#677 Fix missing text on registration page
  config/locales/shared/registrations.en.yml
Labels: bug

#670 Redirect to correct resource page after renewal is completed
  app/controllers/bank_transfer_payment_forms_controller.rb
  app/controllers/cash_payment_forms_controller.rb
  app/controllers/charge_adjust_start_forms_controller.rb
  app/controllers/charge_adjusts_controller.rb
  app/controllers/cheque_payment_forms_controller.rb
  app/controllers/concerns/can_renew_if_possible.rb
  app/controllers/postal_order_payment_forms_controller.rb
  app/controllers/resource_forms_controller.rb
  app/controllers/reversal_forms_controller.rb
  app/controllers/worldpay_missed_payment_forms_controller.rb
  app/controllers/write_off_forms_controller.rb
  app/forms/charge_adjust_start_form.rb
  app/views/charge_adjusts/new.html.erb
  app/views/negative_charge_adjust_forms/new.html.erb
  app/views/positive_charge_adjust_forms/new.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  config/locales/charge_adjusts.en.yml
  config/routes.rb
  spec/factories/registration.rb
  spec/forms/charge_adjust_start_form_spec.rb
  spec/requests/bank_transfer_payment_forms_spec.rb
  spec/requests/cash_payment_forms_spec.rb
  spec/requests/charge_adjusts_spec.rb
  spec/requests/cheque_payment_forms_spec.rb
  spec/requests/payments_spec.rb
  spec/requests/postal_order_payment_forms_spec.rb
  spec/requests/worldpay_missed_payment_forms_spec.rb
  spec/requests/write_off_forms_spec.rb
Labels: bug

#680 Add ability to complete a registration after payment
  app/controllers/concerns/can_complete_if_possible.rb
  app/controllers/resource_forms_controller.rb
  spec/factories/finance_details.rb
  spec/factories/registration.rb
  spec/requests/bank_transfer_payment_forms_spec.rb
  spec/requests/cash_payment_forms_spec.rb
Labels: bug

#681 Rename charge adjust to charge adjust form
  app/controllers/charge_adjust_forms_controller.rb
  app/views/charge_adjust_forms/new.html.erb
  app/views/negative_charge_adjust_forms/new.html.erb
  app/views/positive_charge_adjust_forms/new.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  config/locales/charge_adjust_forms.en.yml
  config/routes.rb
  spec/requests/charge_adjust_forms_spec.rb
Labels: enhancement

#683 Rename payment to payment form
  app/controllers/payment_forms_controller.rb
  app/views/cash_payment_forms/new.html.erb
  app/views/cheque_payment_forms/new.html.erb
  app/views/payment_forms/new.html.erb
  app/views/postal_order_payment_forms/new.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
  app/views/worldpay_missed_payment_forms/new.html.erb
  config/locales/payment_forms.en.yml
  config/routes.rb
  spec/requests/payment_forms_spec.rb
Labels: enhancement

#688 Fix parsing of amounts to flash message
  app/controllers/bank_transfer_payment_forms_controller.rb
  app/controllers/cash_payment_forms_controller.rb
  app/controllers/cheque_payment_forms_controller.rb
  app/controllers/postal_order_payment_forms_controller.rb
  app/controllers/worldpay_missed_payment_forms_controller.rb
Labels: bug

#692 Rename PaymentForm to BasePaymentForm
  app/forms/bank_transfer_payment_form.rb
  app/forms/base_payment_form.rb
  app/forms/cash_payment_form.rb
  app/forms/cheque_payment_form.rb
  app/forms/postal_order_payment_form.rb
  app/forms/worldpay_missed_payment_form.rb
  spec/factories/forms/base_payment_form.rb
  spec/forms/base_payment_form_spec.rb
Labels: enhancement

#694 Remove `renewal` from payment pages
  config/locales/en.yml
Labels: bug

#690 Add form to charge adjust in order to handle validations
  app/controllers/charge_adjust_forms_controller.rb
  app/forms/charge_adjust_form.rb
  app/views/charge_adjust_forms/new.html.erb
  config/locales/charge_adjust_forms.en.yml
  spec/forms/charge_adjust_form_spec.rb
Labels: enhancement

#689 Fix validation on amounts
  app/forms/base_payment_form.rb
  app/forms/concerns/can_have_charge_adjust_attributes.rb
  config/locales/negative_charge_adjust_forms.en.yml
  config/locales/positive_charge_adjust_forms.en.yml
  spec/requests/cheque_payment_forms_spec.rb
Labels: bug

#696 Add validation to payments form
  app/controllers/payment_forms_controller.rb
  app/forms/payment_form.rb
  app/views/payment_forms/new.html.erb
  config/locales/payment_forms.en.yml
  spec/forms/payment_form_spec.rb
Labels: enhancement

#695 Validate amounts to be greater than 1 cent
  app/forms/base_payment_form.rb
  app/forms/concerns/can_have_charge_adjust_attributes.rb
  config/locales/bank_transfer_payment_forms.en.yml
  config/locales/cash_payment_forms.en.yml
  config/locales/cheque_payment_forms.en.yml
  config/locales/negative_charge_adjust_forms.en.yml
  config/locales/positive_charge_adjust_forms.en.yml
  config/locales/postal_order_payment_forms.en.yml
  config/locales/worldpay_missed_payment_forms.en.yml
Labels: bug

#697 Restore links to finance functionality
  app/helpers/action_links_helper.rb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#698 Add validations in inclusion for payments and charge adjust
  app/controllers/payment_forms_controller.rb
  app/forms/charge_adjust_form.rb
  app/forms/payment_form.rb
  app/views/payment_forms/new.html.erb
  config/locales/charge_adjust_forms.en.yml
  config/locales/payment_forms.en.yml
  spec/forms/charge_adjust_form_spec.rb
  spec/forms/payment_form_spec.rb
Labels: enhancement

#701 Fix charge adjustment flash messages
  config/locales/negative_charge_adjust_forms.en.yml
  config/locales/positive_charge_adjust_forms.en.yml
Labels: bug

#705 Remove double validation on amounts
  app/forms/base_payment_form.rb
  app/forms/concerns/can_have_charge_adjust_attributes.rb
  config/locales/bank_transfer_payment_forms.en.yml
  config/locales/cash_payment_forms.en.yml
  config/locales/cheque_payment_forms.en.yml
  config/locales/negative_charge_adjust_forms.en.yml
  config/locales/positive_charge_adjust_forms.en.yml
  config/locales/postal_order_payment_forms.en.yml
  config/locales/worldpay_missed_payment_forms.en.yml
Labels: bug

#699 Add validation for date in the past
  app/forms/base_payment_form.rb
  spec/forms/base_payment_form_spec.rb
Labels: enhancement

#702 Fix renewal bug on charge adjust
  app/controllers/negative_charge_adjust_forms_controller.rb
  app/controllers/positive_charge_adjust_forms_controller.rb
  app/controllers/resource_forms_controller.rb
  app/controllers/worldpay_missed_payment_forms_controller.rb
  app/forms/negative_charge_adjust_form.rb
  app/forms/positive_charge_adjust_form.rb
  spec/factories/renewing_registration.rb
  spec/requests/negative_charge_adjust_forms_spec.rb
  spec/requests/positive_charge_adjust_forms_spec.rb
Labels: bug

#707 Make link to enter a payment consistent and clean
  app/views/finance_details/show.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
Labels: housekeeping

#706 Fix back path for finance details page
  app/helpers/finance_details_helper.rb
  app/views/finance_details/show.html.erb
  spec/helpers/finance_details_helper_spec.rb
Labels: bug

#709 Remove and fix fieldsets with missing legends
  app/views/negative_charge_adjust_forms/new.html.erb
  app/views/positive_charge_adjust_forms/new.html.erb
  app/views/reversal_forms/new.html.erb
  app/views/shared/_payment_form.html.erb
Labels: housekeeping

#710 Update translations for negative charge adjust
  config/locales/negative_charge_adjust_forms.en.yml
Labels: bug

#712 Enable defra-ruby-email in the project
  Gemfile.lock
  app/controllers/application_controller.rb
  config/initializers/waste_carriers_engine.rb
Labels: enhancement

#717 Remove ability to access finance details on unsubmitted renewals
  app/helpers/action_links_helper.rb
  spec/factories/renewing_registration.rb
  spec/helpers/action_links_helper_spec.rb
Labels: bug

#722 Add company info panel to payment pages
  app/views/payment_forms/new.html.erb
Labels: enhancement

#723 Add hint to all text areas
  app/forms/base_payment_form.rb
  app/views/conviction_approval_forms/new.html.erb
  app/views/conviction_rejection_forms/new.html.erb
  app/views/negative_charge_adjust_forms/new.html.erb
  app/views/positive_charge_adjust_forms/new.html.erb
  app/views/registration_conviction_approval_forms/new.html.erb
  app/views/registration_conviction_rejection_forms/new.html.erb
  app/views/reversal_forms/new.html.erb
  app/views/shared/_payment_form.html.erb
  app/views/write_off_forms/new.html.erb
  config/locales/bank_transfer_payment_forms.en.yml
  config/locales/cash_payment_forms.en.yml
  config/locales/cheque_payment_forms.en.yml
  config/locales/conviction_approval_forms.en.yml
  config/locales/conviction_rejection_forms.en.yml
  config/locales/en.yml
  config/locales/negative_charge_adjust_forms.en.yml
  config/locales/positive_charge_adjust_forms.en.yml
  config/locales/postal_order_payment_forms.en.yml
  config/locales/registration_conviction_approval_forms.en.yml
  config/locales/registration_conviction_rejection_forms.en.yml
  config/locales/reversal_forms.en.yml
  config/locales/worldpay_missed_payment_forms.en.yml
  config/locales/write_off_forms.en.yml
  spec/forms/base_payment_form_spec.rb
Labels: enhancement

#724 Hide edit functionality behind a feature toggle
  app/models/ability.rb
  config/feature_toggles.yml
  spec/support/shared_examples/abilities/agency_examples.rb
Labels: housekeeping
