Repository DEFRA/waste-carriers-back-office, pull requests merged in 2020-01, with the labels that each got.

#547 Add view details for registrations payments
  app/controllers/finance_details_controller.rb
  app/helpers/finance_details_helper.rb
  app/views/finance_details/show.html.erb
  app/views/shared/registrations/_balance.html.erb
  app/views/shared/registrations/_charges_and_amendments.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  app/views/shared/registrations/_payment_history.html.erb
  config/initializers/time_formats.rb
  config/locales/finance_details.en.yml
  config/locales/shared/balance.en.yml
  config/locales/shared/charges_and_amendments.en.yml
  config/locales/shared/finance_action_links.en.yml
  config/locales/shared/payment_history.en.yml
  config/routes.rb
  spec/factories/order.rb
  spec/factories/payment.rb
  spec/helpers/finance_details_helper_spec.rb
  spec/requests/finance_details_spec.rb
Labels: enhancement

#548 Add payment details view for transient registrations
  app/controllers/transient_finance_details_controller.rb
  app/presenters/renewing_registration_presenter.rb
  app/views/shared/registrations/_balance.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
  app/views/transient_finance_details/show.html.erb
  config/locales/transient_finance_details.en.yml
  config/routes.rb
  spec/presenters/renewing_registration_presenter_spec.rb
  spec/requests/transient_finance_details_spec.rb
Labels: enhancement

#549 Add and fix links to finance details pages
  app/helpers/action_links_helper.rb
  app/presenters/base_registration_presenter.rb
  app/presenters/renewing_registration_presenter.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_finance_details.html.erb
  config/locales/shared/registrations.en.yml
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/base_registration_presenter_spec.rb
  spec/presenters/renewing_registration_presenter_spec.rb
Labels: enhancement

#550 Isolate finance details resource
  app/controllers/finance_details_controller.rb
  app/controllers/transient_finance_details_controller.rb
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/transient_finance_details.en.yml
  config/routes.rb
  spec/factories/order.rb
  spec/factories/registration.rb
  spec/factories/renewing_registration.rb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/finance_details_spec.rb
  spec/requests/transient_finance_details_spec.rb
Labels: enhancement

#551 Add missing translations of payment types
  config/locales/shared/payment_history.en.yml
Labels: enhancement

#553 Refund Payment - Controller and index page
  app/controllers/concerns/can_fetch_registration_or_transient_registration.rb
  app/controllers/finance_details_controller.rb
  app/controllers/refunds_controller.rb
  app/views/refunds/index.html.erb
  app/views/refunds/new.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  app/views/shared/registrations/_payment_history.html.erb
  config/locales/refunds.en.yml
  config/locales/shared/payment_history.en.yml
  config/locales/shared/payment_types.en.yml
  config/routes.rb
  spec/requests/refunds_spec.rb
Labels: enhancement

#554 Refunds - Implement service
  app/controllers/refunds_controller.rb
  app/models/reports/boxi/payments_serializer.rb
  app/presenters/payment_presenter.rb
  app/services/process_refund_service.rb
  app/views/refunds/index.html.erb
  app/views/refunds/new.html.erb
  app/views/shared/registrations/_payment_history.html.erb
  config/locales/refunds.en.yml
  spec/presenters/payment_presenter_spec.rb
  spec/presenters/reports/boxi/payment_presenter_spec.rb
  spec/requests/refunds_spec.rb
  spec/services/process_refund_service_spec.rb
Labels: enhancement

#556 Update finance details path
  config/routes.rb
  spec/requests/finance_details_spec.rb
Labels: bug

#558 Add refund request to worldpay
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/refunds_controller.rb
  app/services/process_refund_service.rb
  app/services/worldpay/refund_service.rb
  config/locales/refunds.en.yml
  spec/lib/tasks/reports_spec.rb
  spec/requests/refunds_spec.rb
  spec/services/process_refund_service_spec.rb
  spec/services/worldpay/refund_service_spec.rb
  spec/support/webmock.rb
Labels: enhancement

#559 Add permissions checks to refund
  app/controllers/refunds_controller.rb
  app/models/ability.rb
  app/views/shared/registrations/_finance_action_links.html.erb
  spec/requests/refunds_spec.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: enhancement

#562 Reword flash error message for worldpay refunds
  config/locales/refunds.en.yml
Labels: enhancement

#566 Reword copy cards link
  config/locales/shared/registrations.en.yml
Labels: enhancement

#565 Hide refund button unless overpayment
  app/helpers/action_links_helper.rb
  app/views/shared/registrations/_finance_action_links.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#561 Calculate the correct amount for refund
  app/services/process_refund_service.rb
  app/services/worldpay/refund_service.rb
  spec/factories/finance_details.rb
  spec/factories/renewing_registration.rb
  spec/requests/refunds_spec.rb
  spec/services/process_refund_service_spec.rb
  spec/services/worldpay/refund_service_spec.rb
Labels: enhancement

#563 Fix code to render error flash messages
  app/views/finance_details/show.html.erb
Labels: enhancement

#514 Activate and deactivate back office users
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/user_activations_controller.rb
  app/controllers/user_activity_controller.rb
  app/controllers/user_deactivations_controller.rb
  app/models/ability.rb
  app/models/concerns/can_behave_like_user.rb
  app/models/user.rb
  app/views/pages/deactivated.html.erb
  app/views/user_activations/new.html.erb
  app/views/user_deactivations/new.html.erb
  app/views/users/index.html.erb
  config/locales/pages/deactivated.en.yml
  config/locales/user_activations.en.yml
  config/locales/user_deactivations.en.yml
  config/locales/users.en.yml
  config/routes.rb
  spec/factories/user.rb
  spec/models/ability_spec.rb
  spec/models/user_spec.rb
  spec/requests/dashboards_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/routes_spec.rb
  spec/requests/sessions_spec.rb
  spec/requests/user_activations_spec.rb
  spec/requests/user_deactivations_spec.rb
  spec/support/shared_examples/abilities/active_and_inactive_examples.rb
Labels: enhancement

#568 Update view on refund details
  app/controllers/refunds_controller.rb
  app/presenters/refund_presenter.rb
  app/views/refunds/new.html.erb
  config/locales/refunds.en.yml
  spec/presenters/refund_presenter_spec.rb
Labels: enhancement

#570 Edit permissions for cease and revoke
  app/models/ability.rb
  spec/support/shared_examples/abilities/agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: enhancement

#573 Add sign-out link to the deactivated page
  app/views/pages/deactivated.html.erb
  config/locales/pages/deactivated.en.yml
Labels: bug

#571 Fix buttons vertical distance
  app/assets/stylesheets/partials/_buttons.scss
  app/views/shared/registrations/_finance_action_links.html.erb
Labels: accessibility, enhancement

#569 Change back office user role
  app/controllers/user_activity_controller.rb
  app/controllers/user_roles_controller.rb
  app/helpers/users_helper.rb
  app/models/ability.rb
  app/models/concerns/can_behave_like_user.rb
  app/models/user.rb
  app/views/shared/_select_role.html.erb
  app/views/user_roles/new.html.erb
  app/views/users/index.html.erb
  config/locales/en.yml
  config/locales/user_roles.en.yml
  config/locales/users.en.yml
  config/routes.rb
  spec/helpers/users_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/user_roles_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/agency_super_examples.rb
  spec/support/shared_examples/abilities/below_agency_super_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
  spec/support/shared_examples/abilities/finance_super_examples.rb
Labels: enhancement

#574 Add 'invite new user' feature
  app/controllers/user_invitations_controller.rb
  app/controllers/user_roles_controller.rb
  app/helpers/users_helper.rb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/invitations/new.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.txt.erb
  app/views/users/index.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  config/locales/users.en.yml
  config/routes.rb
  spec/requests/user_invitations_spec.rb
Labels: enhancement

#575 Add user.deactivated? method
  app/controllers/user_deactivations_controller.rb
  app/models/ability.rb
  app/models/user.rb
  app/views/users/index.html.erb
  spec/models/ability_spec.rb
  spec/models/user_spec.rb
  spec/support/shared_examples/abilities/active_and_inactive_examples.rb
Labels: housekeeping

#578 Use correct worldpay information
  .env.example
  .travis.yml
  app/services/process_refund_service.rb
  app/services/worldpay/refund_service.rb
  config/application.rb
  spec/services/process_refund_service_spec.rb
  spec/services/worldpay/refund_service_spec.rb
Labels: enhancement

#576 Add new method for finance_details check
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: bug

#579 Add missing page titles
  config/locales/finance_details.en.yml
  config/locales/refunds.en.yml
Labels: bug

#577 Housekeeping ceased and removed links helpers
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
  spec/helpers/action_links_helper_spec.rb
Labels: housekeeping

#582 Remove links for release
  app/helpers/action_links_helper.rb
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#583 Fix thead and tbody
  app/views/shared/registrations/_balance.html.erb
  app/views/shared/registrations/_charges_and_amendments.html.erb
  app/views/shared/registrations/_main_people_details.html.erb
  app/views/shared/registrations/_payment_history.html.erb
Labels: bug

#584 Fix thead and tbody on refunds table
  app/views/refunds/index.html.erb
Labels: bug

#585 Fixes to refund functionality
  app/controllers/refunds_controller.rb
  app/services/process_refund_service.rb
  app/views/finance_details/show.html.erb
  spec/services/process_refund_service_spec.rb
Labels: bug

#586 Add process payment button to action list
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/shared/registrations.en.yml
Labels: bug

#588 Add missing titles to new user invite pages
  config/locales/devise_invitable.en.yml
Labels: bug

#591 Fix wonky validation on user invite form
  app/controllers/user_invitations_controller.rb
  app/views/devise/invitations/new.html.erb
Labels: bug

#590 Fix default email protocol
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: bug

#592 Add 'developer' user role
  app/models/ability.rb
  app/models/user.rb
  app/services/user_migration_service.rb
  config/locales/en.yml
  config/locales/user_migrations.en.yml
  config/locales/user_roles.en.yml
  config/locales/users.en.yml
  db/seeds/users.json
  spec/factories/user.rb
  spec/models/ability_spec.rb
  spec/services/user_migration_service_spec.rb
  spec/support/shared_examples/abilities/developer_examples.rb
  spec/support/shared_examples/abilities/non_developer_examples.rb
Labels: enhancement

#593 Add support for mocking external services
  Gemfile
  Gemfile.lock
  config/initializers/defra_ruby_mocks.rb
  config/initializers/waste_carriers_engine.rb
  config/routes.rb
Labels: enhancement

#594 Set up ConvictionImportService
  app/services/conviction_import_service.rb
  spec/services/conviction_import_service_spec.rb
Labels: enhancement

#596 Fix flash messages colours
  app/assets/stylesheets/partials/_flash-messages.scss
Labels: bug

#598 Fixes to refunds
  app/presenters/payment_presenter.rb
  app/services/process_refund_service.rb
  spec/presenters/payment_presenter_spec.rb
Labels: bug

#599 Unify refund headers
  app/views/refunds/new.html.erb
  config/locales/refunds.en.yml
Labels: enhancement

#595 Finance - Write Offs
  app/controllers/write_off_forms_controller.rb
  app/forms/write_off_form.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/services/process_write_off_service.rb
  app/views/refunds/index.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  app/views/write_off_forms/new.html.erb
  config/application.rb
  config/locales/write_off_forms.en.yml
  config/routes.rb
  spec/forms/write_off_form_spec.rb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/write_off_forms_spec.rb
  spec/services/process_write_off_service_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
Labels: enhancement

#601 Add page to import convictions
  app/controllers/conviction_imports_controller.rb
  app/views/conviction_imports/new.html.erb
  app/views/dashboards/index.html.erb
  app/views/layouts/application.html.erb
  config/locales/conviction_imports.en.yml
  config/locales/en.yml
  config/routes.rb
  spec/requests/conviction_imports_spec.rb
Labels: enhancement

#604 Update mocks engine to support Worldpay
  Gemfile
  Gemfile.lock
  config/application.rb
  config/initializers/defra_ruby_mocks.rb
Labels: enhancement

#600 Add resource scope
  app/controllers/concerns/can_fetch_registration_or_transient_registration.rb
  app/controllers/concerns/can_fetch_resource.rb
  app/controllers/finance_details_controller.rb
  app/controllers/refunds_controller.rb
  app/controllers/write_off_forms_controller.rb
  app/views/dashboards/index.html.erb
  app/views/finance_details/show.html.erb
  app/views/refunds/index.html.erb
  app/views/refunds/new.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  app/views/write_off_forms/new.html.erb
  config/routes.rb
  spec/requests/finance_details_spec.rb
  spec/requests/refunds_spec.rb
  spec/requests/write_off_forms_spec.rb
Labels: enhancement, housekeeping

#605 Fix bug in BOXI export
  app/presenters/reports/boxi/sign_off_presenter.rb
  spec/presenters/reports/boxi/sign_off_presenter_spec.rb
  spec/services/reports/generate_boxi_files_service_spec.rb
Labels: bug

#606 Fix typo in boxi default filename
  config/application.rb
Labels: bug

#609 Update mock engine to get Worldpay refund support
  Gemfile
  Gemfile.lock
Labels: enhancement

#611 Fix dates in boxi export
  app/models/reports/boxi/order_items_serializer.rb
  app/models/reports/boxi/orders_serializer.rb
  app/presenters/reports/boxi/key_person_presenter.rb
  app/presenters/reports/boxi/order_item_presenter.rb
  app/presenters/reports/boxi/order_presenter.rb
  spec/models/reports/boxi/order_items_serializer_spec.rb
  spec/models/reports/boxi/orders_serializer_spec.rb
  spec/presenters/reports/boxi/key_person_presenter_spec.rb
  spec/presenters/reports/boxi/order_item_presenter_spec.rb
  spec/presenters/reports/boxi/order_presenter_spec.rb
  spec/presenters/reports/boxi/payment_presenter_spec.rb
  spec/presenters/reports/boxi/registration_presenter_spec.rb
  spec/presenters/reports/boxi/sign_off_presenter_spec.rb
Labels: bug

#612 Set a worldpay response type
  app/services/process_refund_service.rb
  spec/services/process_refund_service_spec.rb
Labels: bug

#616 ConvictionImportService validates DOB if provided
  app/services/conviction_import_service.rb
  spec/services/conviction_import_service_spec.rb
Labels: bug

#617 Redirect to BO dashboard after creating new account
  app/controllers/application_controller.rb
Labels: bug

#613 Fix format of amounts in boxi export
  app/presenters/payment_presenter.rb
  app/presenters/reports/boxi/order_item_presenter.rb
  app/presenters/reports/boxi/order_presenter.rb
  app/presenters/reports/boxi/payment_presenter.rb
  app/presenters/reports/boxi/registration_presenter.rb
  spec/presenters/reports/boxi/order_item_presenter_spec.rb
  spec/presenters/reports/boxi/order_presenter_spec.rb
  spec/presenters/reports/boxi/payment_presenter_spec.rb
  spec/presenters/reports/boxi/registration_presenter_spec.rb
Labels: bug

#614 Add guard clause to missing object
  app/models/reports/boxi/addresses_serializer.rb
  app/models/reports/boxi/key_people_serializer.rb
  app/models/reports/boxi/order_items_serializer.rb
  app/models/reports/boxi/orders_serializer.rb
  app/models/reports/boxi/payments_serializer.rb
  app/models/reports/boxi/sign_offs_serializer.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
  spec/models/reports/boxi/key_people_serializer_spec.rb
  spec/models/reports/boxi/order_items_serializer_spec.rb
  spec/models/reports/boxi/orders_serializer_spec.rb
  spec/models/reports/boxi/payments_serializer_spec.rb
  spec/models/reports/boxi/registrations_serializer_spec.rb
  spec/models/reports/boxi/sign_offs_serializer_spec.rb
Labels: bug

#619 Fix broken 'Finished' link on renewal end pages
  Gemfile.lock
  app/helpers/waste_carriers_engine/journey_links_helper.rb
  config/locales/waste_carriers_engine.en.yml
  spec/helpers/waste_carriers_engine/journey_links_helper_spec.rb
Labels: bug

#622 Fix links to new payments
  app/forms/payment_form.rb
  app/views/shared/registrations/_action_links_panel.html.erb
  app/views/shared/registrations/_finance_action_links.html.erb
  app/views/shared/registrations/_pending_payment_panel.html.erb
Labels: enhancement

#625 More fixes to BOXI
  app/models/reports/boxi/addresses_serializer.rb
  app/models/reports/boxi/base_serializer.rb
  app/models/reports/boxi/key_people_serializer.rb
  app/models/reports/boxi/order_items_serializer.rb
  app/models/reports/boxi/orders_serializer.rb
  app/models/reports/boxi/payments_serializer.rb
  app/models/reports/boxi/registrations_serializer.rb
  app/models/reports/boxi/sign_offs_serializer.rb
  app/services/reports/generate_boxi_files_service.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
  spec/models/reports/boxi/key_people_serializer_spec.rb
  spec/models/reports/boxi/order_items_serializer_spec.rb
  spec/models/reports/boxi/orders_serializer_spec.rb
  spec/models/reports/boxi/payments_serializer_spec.rb
  spec/models/reports/boxi/registrations_serializer_spec.rb
Labels: enhancement

#626 Remove change to wrong presenter
  app/presenters/payment_presenter.rb
Labels: bug

#627 Temp. fix for cc-test-reporter & SimpleCov 0.18
  Gemfile
  Gemfile.lock
Labels: housekeeping

#628 Fix changelog generator
  lib/tasks/changelog.rake
Labels: housekeeping

#630 Actually fix redirect after accepting user invite
  app/controllers/application_controller.rb
  spec/requests/user_invitations_spec.rb
Labels: bug

#634 Fix parsing carriage returns in BOXI export
  app/models/reports/boxi/base_serializer.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
  spec/models/reports/boxi/key_people_serializer_spec.rb
  spec/models/reports/boxi/order_items_serializer_spec.rb
  spec/models/reports/boxi/orders_serializer_spec.rb
  spec/models/reports/boxi/payments_serializer_spec.rb
  spec/models/reports/boxi/registrations_serializer_spec.rb
Labels: bug
