Repository DEFRA/waste-carriers-back-office, pull requests merged in 2020-03, with the labels that each got.

#726 Clarify payment details access
  app/helpers/action_links_helper.rb
  spec/helpers/action_links_helper_spec.rb
Labels: bug

#728 Remove Cease & revoke link from dashboard
  app/views/dashboards/index.html.erb
Labels: housekeeping

#729 Remove Transfer link from dashboard page
  app/views/dashboards/index.html.erb
Labels: housekeeping

#730 Fix Transfer registration page rendering
  app/views/registration_transfers/new.html.erb
  app/views/registration_transfers/success.html.erb
Labels: bug

#731 Fix url to worldpay missed payment form
  app/views/renewing_registrations/show.html.erb
Labels: bug

#732 Fix redirect path to summary-page
  app/controllers/worldpay_escapes_controller.rb
  spec/requests/worldpay_escapes_spec.rb
Labels: bug

#734 Add validation on length for conviction reason
  app/forms/conviction_reason_form.rb
  config/locales/conviction_approval_forms.en.yml
  config/locales/conviction_rejection_forms.en.yml
Labels: enhancement

#739 Switch to SonarCloud from CodeClimate
  .travis.yml
  README.md
  sonar-project.properties
Labels: housekeeping

#745 Hide start new registration behind feature toggle
  Gemfile.lock
  config/feature_toggles.yml
Labels: housekeeping

#747 Add charge value for New registrations
  config/application.rb
Labels: enhancement

#746 Fix conviction approval access permissions
  app/controllers/convictions_controller.rb
  app/controllers/convictions_dashboards_controller.rb
  app/models/ability.rb
  app/views/layouts/application.html.erb
  spec/requests/conviction_approval_forms_spec.rb
  spec/requests/conviction_rejection_forms_spec.rb
  spec/requests/convictions_dashboards_spec.rb
  spec/requests/convictions_spec.rb
  spec/requests/registration_conviction_approval_forms_spec.rb
  spec/requests/registration_conviction_rejection_forms_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/below_agency_with_refund_examples.rb
Labels: bug

#748 Use existing ENV variable for Registration charges
  config/application.rb
Labels: enhancement

#755 Use sequence to generate reg_identifier
  spec/factories/registration.rb
Labels: bug

#764 Complete a registration if possible at write off
  app/controllers/write_off_forms_controller.rb
  app/forms/write_off_form.rb
  app/views/write_off_forms/new.html.erb
  spec/forms/write_off_form_spec.rb
  spec/requests/write_off_forms_spec.rb
Labels: bug

#765 Add style for blue application received box
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_govuk-box-highlight.scss
Labels: enhancement

#777 Align data in the table correctly
  app/views/convictions/index.html.erb
Labels: bug

#784 Capitalise order item descriptions properly
  app/views/shared/registrations/_charges_and_amendments.html.erb
  app/views/shared/registrations/_finance_details.html.erb
Labels: bug

#786 Fix typo on conviction rejection page
  config/locales/conviction_rejection_forms.en.yml
Labels: bug
