Repository DEFRA/waste-carriers-back-office, pull requests merged in 2020-07, with the labels that each got.

#925 Changes need to support switch to 'main' branch
  Gemfile
  Gemfile.lock
  README.md
Labels: housekeeping

#922 Integrate feature toggles engine
  Gemfile
  Gemfile.lock
  app/models/ability.rb
  config/application.rb
  config/initializers/defra_ruby_features.rb
  config/routes.rb
Labels: enhancement

#927 Fix defra-ruby-features ActiveRecord error
  Gemfile.lock
Labels: bug

#928 Add link to menu to feature toggles
  app/views/layouts/application.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/support/shared_examples/abilities/developer_examples.rb
  spec/support/shared_examples/abilities/non_developer_examples.rb
Labels: enhancement

#930 Update link to privacy policy
  app/helpers/ad_privacy_policy_helper.rb
Labels: bug

#933 Toggle where new registration redirects to
  app/controllers/ad_privacy_policy_controller.rb
  app/helpers/waste_carriers_engine/ad_privacy_policy_helper.rb
  app/presenters/ad_privacy_policy_presenter.rb
  app/views/ad_privacy_policy/show.html.erb
  spec/helpers/waste_carriers_engine/ad_privacy_policy_helper_spec.rb
  spec/presenters/ad_privacy_policy_presenter_spec.rb
Labels: enhancement

#941 Update defra-ruby-aws to encryption configurable
  .env.example
  Gemfile.lock
  config/initializers/defra_ruby_aws.rb
Labels: enhancement

#942 Update defra-ruby-alert to use blocklist
  Gemfile.lock
  config/initializers/waste_carriers_engine.rb
Labels: housekeeping

#944 Switch defra-ruby-features to rubygems
  Gemfile
  Gemfile.lock
Labels: housekeeping

#945 Remove link to certificate from renewal complete
  Gemfile.lock
Labels: enhancement

#946 Update privacy policy link txt in AD page
  config/locales/ad_privacy_policy.en.yml
Labels: enhancement

#950 Allow individual pages to include page_scripts
  app/views/layouts/application.html.erb
Labels: enhancement

#948 Add payment confirmation email to view details
  app/views/registrations/show.html.erb
  app/views/shared/registrations/_receipt_email_panel.html.erb
  config/locales/shared/registrations.en.yml
Labels: enhancement

#952 Remove create new reg. link if feature disabled
  app/presenters/ad_privacy_policy_presenter.rb
  app/views/dashboards/index.html.erb
  spec/presenters/ad_privacy_policy_presenter_spec.rb
Labels: bug

#953 Extend back office renewal grace period
  Gemfile
  Gemfile.lock
  app/services/waste_carriers_engine/expiry_check_service.rb
  spec/services/waste_carriers_engine/expiry_check_service_spec.rb
Labels: enhancement

#958 Add extend grace window toggle to .yml file
  config/feature_toggles.yml
Labels: housekeeping

#959 Tell engine we are the back-office
  Gemfile.lock
  config/initializers/waste_carriers_engine.rb
Labels: enhancement

#961 Update payment confirmation behaviour
  Gemfile.lock
Labels: enhancement

#924 Add final reminder letters dashboard
  .env.example
  .travis.yml
  app/assets/stylesheets/letters.scss
  app/controllers/final_reminder_letters_exports_controller.rb
  app/controllers/letters_controller.rb
  app/models/ability.rb
  app/models/final_reminder_letters_export.rb
  app/presenters/final_reminder_letters_export_presenter.rb
  app/services/final_reminder_letters_bulk_pdf_service.rb
  app/services/final_reminder_letters_export_cleaner_service.rb
  app/services/final_reminder_letters_export_service.rb
  app/views/final_reminder_letters/_final_reminder_letter_content.html.erb
  app/views/final_reminder_letters/bulk.html.erb
  app/views/final_reminder_letters_exports/index.html.erb
  app/views/letters/index.html.erb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  config/initializers/time_formats.rb
  config/locales/final_reminder_letters_exports.en.yml
  config/locales/letters.en.yml
  config/routes.rb
  config/schedule.rb
  lib/tasks/letters.rake
  spec/factories/final_reminder_letters_export.rb
  spec/models/final_reminder_letters_export_spec.rb
  spec/presenters/final_reminder_letters_export_presenter_spec.rb
  spec/requests/final_reminder_letters_exports_spec.rb
  spec/requests/letters_spec.rb
  spec/schedule_spec.rb
  spec/services/final_reminder_letters_bulk_pdf_service_spec.rb
  spec/services/final_reminder_letters_export_cleaner_service_spec.rb
  spec/services/final_reminder_letters_export_service_spec.rb
Labels: enhancement

#962 Generate renewal token when one is requested
  Gemfile.lock
  app/mailers/renewal_reminder_mailer.rb
  spec/mailers/renewal_reminder_mailer_spec.rb
Labels: enhancement

#965 Add letters link to nav
  app/views/layouts/application.html.erb
  config/locales/en.yml
Labels: enhancement

#956 Add template for non-AD renewal letters
  app/assets/images/logo_ea.png
  app/assets/stylesheets/letters.scss
  app/presenters/final_reminder_letter_presenter.rb
  app/services/final_reminder_letters_bulk_pdf_service.rb
  app/views/final_reminder_letters/_final_reminder_letter_content.html.erb
  app/views/final_reminder_letters/_styles.html.erb
  app/views/final_reminder_letters/bulk.html.erb
  config/locales/final_reminder_letters.en.yml
  spec/presenters/final_reminder_letter_presenter_spec.rb
  spec/services/final_reminder_letters_bulk_pdf_service_spec.rb
  spec/services/final_reminder_letters_export_service_spec.rb
Labels: enhancement

#964 Merge email_reminders and renew_via_magic_link
  app/views/layouts/application.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/feature_toggles.yml
  lib/tasks/email.rake
  spec/mailers/renewal_reminder_mailer_spec.rb
Labels: housekeeping

#968 Update whenever to latest
  Gemfile
  Gemfile.lock
Labels: housekeeping

#967 Do not copy receipt_email when init. renewal
  Gemfile.lock
Labels: bug

#971 Fix broken renewal link panel
  app/views/registrations/show.html.erb
  app/views/shared/registrations/_renewal_magic_link_panel.html.erb
  config/locales/shared/registrations.en.yml
Labels: bug

#966 Implement bulk letter export for AD renewal reminders
  app/controllers/ad_reminder_letters_exports_controller.rb
  app/controllers/digital_reminder_letters_exports_controller.rb
  app/controllers/final_reminder_letters_exports_controller.rb
  app/controllers/letters_controller.rb
  app/models/ability.rb
  app/models/ad_reminder_letters_export.rb
  app/models/digital_reminder_letters_export.rb
  app/models/reminder_letters_export.rb
  app/presenters/reminder_letter_presenter.rb
  app/presenters/reminder_letters_export_presenter.rb
  app/services/ad_reminder_letters_bulk_pdf_service.rb
  app/services/ad_reminder_letters_export_cleaner_service.rb
  app/services/ad_reminder_letters_export_service.rb
  app/services/digital_reminder_letters_bulk_pdf_service.rb
  app/services/digital_reminder_letters_export_cleaner_service.rb
  app/services/digital_reminder_letters_export_service.rb
  app/services/final_reminder_letters_export_service.rb
  app/services/reminder_letters_bulk_pdf_service.rb
  app/services/reminder_letters_export_cleaner_service.rb
  app/services/reminder_letters_export_service.rb
  app/views/ad_reminder_letters/_ad_reminder_letter_content.html.erb
  app/views/ad_reminder_letters/_styles.html.erb
  app/views/ad_reminder_letters/bulk.html.erb
  app/views/ad_reminder_letters_exports/index.html.erb
  app/views/digital_reminder_letters/_digital_reminder_letter_content.html.erb
  app/views/digital_reminder_letters/_styles.html.erb
  app/views/digital_reminder_letters/bulk.html.erb
  app/views/digital_reminder_letters_exports/index.html.erb
  app/views/layouts/application.html.erb
  app/views/letters/index.html.erb
  config/application.rb
  config/locales/ad_reminder_letters.en.yml
  config/locales/ad_reminder_letters_exports.en.yml
  config/locales/digital_reminder_letters.en.yml
  config/locales/digital_reminder_letters_exports.en.yml
  config/locales/letters.en.yml
  config/locales/reminder_letters_exports.en.yml
  config/routes.rb
  config/schedule.rb
  lib/tasks/letters.rake
  spec/factories/ad_reminder_letters_export.rb
  spec/factories/digital_reminder_letters_export.rb
  spec/models/ad_reminder_letters_export_spec.rb
  spec/models/digital_reminder_letters_export_spec.rb
  spec/presenters/reminder_letter_presenter_spec.rb
  spec/presenters/reminder_letters_export_presenter_spec.rb
  spec/requests/ad_reminder_letters_exports_spec.rb
  spec/requests/digital_reminder_letters_exports_spec.rb
  spec/requests/final_reminder_letters_exports_spec.rb
  spec/schedule_spec.rb
  spec/services/ad_reminder_letters_bulk_pdf_service_spec.rb
  spec/services/ad_reminder_letters_export_cleaner_service_spec.rb
  spec/services/ad_reminder_letters_export_service_spec.rb
  spec/services/digital_reminder_letters_bulk_pdf_service_spec.rb
  spec/services/digital_reminder_letters_export_cleaner_service_spec.rb
  spec/services/digital_reminder_letters_export_service_spec.rb
  spec/support/shared_examples/abilities/agency_examples.rb
  spec/support/shared_examples/abilities/finance_admin_examples.rb
  spec/support/shared_examples/abilities/finance_examples.rb
Labels: enhancement

#973 Update flash message logic
  app/controllers/bank_transfer_payment_forms_controller.rb
  app/controllers/cancels_controller.rb
  app/controllers/cash_payment_forms_controller.rb
  app/controllers/cheque_payment_forms_controller.rb
  app/controllers/concerns/.keep
  app/controllers/concerns/can_set_flash_messages.rb
  app/controllers/conviction_imports_controller.rb
  app/controllers/negative_charge_adjust_forms_controller.rb
  app/controllers/positive_charge_adjust_forms_controller.rb
  app/controllers/postal_order_payment_forms_controller.rb
  app/controllers/refunds_controller.rb
  app/controllers/resend_renewal_email_controller.rb
  app/controllers/reversal_forms_controller.rb
  app/controllers/worldpay_missed_payment_forms_controller.rb
  app/controllers/write_off_forms_controller.rb
  app/views/conviction_imports/new.html.erb
  app/views/finance_details/show.html.erb
  app/views/shared/_flash_messages.html.erb
  app/views/transient_finance_details/show.html.erb
Labels: enhancement

#975 Only display renew/new reg links to those who can use them
  app/views/shared/registrations/_expired_panel.html.erb
Labels: bug

#972 Show err msg when resend reminder to empty contact
  app/controllers/resend_renewal_email_controller.rb
  app/lib/exceptions.rb
  app/mailers/renewal_reminder_mailer.rb
  app/views/dashboards/index.html.erb
  app/views/registrations/show.html.erb
  config/application.rb
  config/locales/resend_renewal_email.en.yml
  spec/mailers/renewal_reminder_mailer_spec.rb
  spec/requests/resend_renewal_email_spec.rb
Labels: enhancement

#976 Show err msg when resend reminder to AD contact
  app/controllers/resend_renewal_email_controller.rb
  app/lib/exceptions.rb
  app/mailers/renewal_reminder_mailer.rb
  config/locales/resend_renewal_email.en.yml
  spec/mailers/renewal_reminder_mailer_spec.rb
  spec/requests/resend_renewal_email_spec.rb
Labels: enhancement

#980 Don't allow resending/sharing of magic link emails that users can't use
  app/helpers/action_links_helper.rb
  app/models/waste_carriers_engine/registration.rb
  app/services/waste_carriers_engine/expiry_check_service.rb
  app/views/registrations/show.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  spec/helpers/action_links_helper_spec.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/services/waste_carriers_engine/expiry_check_service_spec.rb
Labels: bug

#981 Add missing quote
  app/views/ad_reminder_letters/_ad_reminder_letter_content.html.erb
Labels: bug

#982 Don't hardcode EA email into digital reminder letter
  app/presenters/reminder_letter_presenter.rb
  app/views/digital_reminder_letters/_digital_reminder_letter_content.html.erb
  config/locales/digital_reminder_letters.en.yml
  spec/presenters/reminder_letter_presenter_spec.rb
Labels: bug

#983 Don't enforce expiry date uniqueness across exports
  app/models/ad_reminder_letters_export.rb
  app/models/digital_reminder_letters_export.rb
  app/models/reminder_letters_export.rb
  spec/models/ad_reminder_letters_export_spec.rb
  spec/models/digital_reminder_letters_export_spec.rb
Labels: bug

#984 Update default letter config to allow more leeway
  config/application.rb
Labels: enhancement
