Repository DEFRA/waste-carriers-back-office, pull requests merged in 2022-04, with the labels that each got.

#1305 Fix spec that broke with Mongoid upgrade
  Gemfile.lock
  spec/helpers/action_links_helper_spec.rb
Labels: dependencies

#1311 Adjust request spec to align with engine changes
  spec/requests/renewing_registrations_spec.rb
Labels: enhancement

#1309 Adjust wording on registration details page
  config/locales/shared/registrations.en.yml
Labels: enhancement

#1322 Force GitHub to run apt-get update before installing dependencies
  .github/workflows/ci.yml
Labels: housekeeping
