Repository DEFRA/waste-carriers-back-office, pull requests merged in 2022-09, with the labels that each got.

#1430 Adding in telephone search specs
  config/locales/dashboard.en.yml
  spec/services/search_service_spec.rb
Labels: enhancement

#1434 Fix daily finance report
  app/models/reports/base_serializer.rb
  app/models/reports/monthly_finance_report_serializer.rb
  app/presenters/reports/finance_report_presenter.rb
  app/services/reports/finance_stats_service.rb
  spec/models/reports/daily_finance_report_serializer_spec.rb
  spec/models/reports/monthly_finance_report_serializer_spec.rb
  spec/services/reports/charges_by_type_service_spec.rb
  spec/services/reports/finance_stats_service_spec.rb
  spec/services/reports/payments_by_type_service_spec.rb
  spec/support/shared_contexts/finance_stats_order_data.rb
  spec/support/shared_contexts/finance_stats_payment_data.rb
Labels: bug

#1435 Fix daily finance reports
  app/presenters/reports/finance_report_presenter.rb
  spec/presenters/reports/finance_report_presenter_spec.rb
  spec/services/reports/finance_stats_service_spec.rb
Labels: housekeeping

#1436 Add renewal stats to the monthly finance report
  app/models/reports/daily_finance_report_serializer.rb
  app/models/reports/monthly_finance_report_serializer.rb
  app/presenters/reports/finance_report_presenter.rb
  app/services/reports/finance_stats_service.rb
  spec/models/reports/monthly_finance_report_serializer_spec.rb
  spec/presenters/reports/finance_report_presenter_spec.rb
  spec/services/reports/finance_stats_service_spec.rb
  spec/support/shared_contexts/finance_stats_order_data.rb
Labels: enhancement

#1437 Finance reports renewals stats
  app/presenters/reports/finance_report_presenter.rb
  spec/presenters/reports/finance_report_presenter_spec.rb
Labels: bug

#1439 Hide worldpay refunds if govpay active and vice-versa
  app/controllers/refunds_controller.rb
  app/helpers/action_links_helper.rb
  spec/factories/finance_details.rb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/refunds_spec.rb
Labels: enhancement

#1441 Merge govpay branch into main
  .ruby-version
  Gemfile
  Gemfile.lock
  app/controllers/refunds_controller.rb
  app/forms/base_payment_form.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/services/process_refund_service.rb
  config/application.rb
  config/initializers/defra_ruby_mocks.rb
  config/locales/refunds.en.yml
  config/locales/shared/payment_types.en.yml
  spec/factories/finance_details.rb
  spec/factories/payment.rb
  spec/factories/renewing_registration.rb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/refunds_spec.rb
  spec/services/process_refund_service_spec.rb
Labels: housekeeping

#1442 Use main engine branch
  Gemfile
  Gemfile.lock
Labels: bug
