Repository DEFRA/waste-carriers-back-office, pull requests merged in 2023-06, with the labels that each got.

#1635 find renewal dates message to be displayed only for upper registrations
  app/views/shared/registrations/_company_details_panel.html.erb
Labels: bug

#1637 Check refund status button permissions
  app/helpers/action_links_helper.rb
  spec/helpers/action_links_helper_spec.rb
Labels: bug

#1641 Puma in dev
  Gemfile
  Gemfile.lock
Labels: housekeeping

#1651 Fix/area query
  Gemfile.lock
  lib/tasks/lookups.rake
  lib/tasks/trim.rake
  lib/timed_service_runner.rb
  spec/forms/registration_transfer_form_spec.rb
  spec/lib/tasks/lookups_spec.rb
  spec/lib/timed_service_runner_spec.rb
Labels: bug

#1657 Adding a check to ensure method exists before calling it
  app/presenters/base_registration_presenter.rb
Labels: bug

#1650 RUBY-2500: feature toggle for registration transfer link
  app/helpers/action_links_helper.rb
Labels: enhancement
