Repository DEFRA/waste-carriers-back-office, pull requests merged in 2023-12, with the labels that each got.

#1805 Chore/ruby 2770 controller permission checks
  app/controllers/application_controller.rb
  app/controllers/back_office_forms_controller.rb
  app/controllers/cease_or_revoke_forms_controller.rb
  app/controllers/ceased_or_revoked_confirm_forms_controller.rb
  app/controllers/concerns/can_act_as_back_office_page.rb
  app/controllers/confirm_edit_cancelled_forms_controller.rb
  app/controllers/copy_cards_bank_transfer_forms_controller.rb
  app/controllers/copy_cards_forms_controller.rb
  app/controllers/copy_cards_order_completed_forms_controller.rb
  app/controllers/copy_cards_payment_forms_controller.rb
  app/controllers/edit_bank_transfer_forms_controller.rb
  app/controllers/edit_forms_controller.rb
  spec/requests/cease_or_revoke_forms_spec.rb
  spec/requests/ceased_or_revoked_confirm_forms_spec.rb
  spec/requests/confirm_edit_cancelled_forms_spec.rb
  spec/requests/copy_cards_bank_transfer_forms_spec.rb
  spec/requests/copy_cards_forms_spec.rb
  spec/requests/copy_cards_payment_forms_spec.rb
  spec/requests/edit_bank_transfer_forms_spec.rb
  spec/requests/edit_forms_spec.rb
  spec/support/shared_examples/user_not_authorised.rb
  spec/support/shared_examples/user_not_logged_in.rb
Labels: housekeeping

#1807 Handle nil user when checking role permissions
  app/models/ability.rb
  spec/services/waste_carriers_engine/edit_registration_permission_checks_service_spec.rb
Labels: bug

#1808 [RUBY-2795] view communication history page
  app/controllers/communication_records_controller.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/views/communication_records/index.html.erb
  app/views/shared/registrations/_action_links_panel.html.erb
  config/locales/communication_records.en.yml
  config/locales/shared/registrations.en.yml
  config/routes.rb
  spec/factories/communication_record.rb
  spec/helpers/action_links_helper_spec.rb
  spec/models/ability_spec.rb
  spec/requests/communication_records_spec.rb
Labels: enhancement

#1811 [RUBY-2779] disabling broken auto sign in for back office users after password reset
  Gemfile.lock
  config/initializers/devise.rb
Labels: bug
