Repository DEFRA/waste-carriers-back-office, pull requests merged in 2023-11, with the labels that each got.

#1762 Fix/govpay logging
  Gemfile.lock
  spec/services/govpay_refund_details_service_spec.rb
Labels: housekeeping

#1763 Fix export of reverse payment permissions
  lib/tasks/export_roles_permissions_csv.rake
Labels: bug

#1765 Version 1.23.0
  CHANGELOG.md
Labels: housekeeping

#1767 Bump govpay gem version
  Gemfile
  Gemfile.lock
  spec/services/govpay_refund_details_service_spec.rb
  spec/services/govpay_refund_service_spec.rb
Labels: bug

#1764 feature/RUBY-2763_delete_pending_payment_regs_7_years
  app/services/remove_deletable_registrations_service.rb
  spec/services/remove_deletable_registrations_service_spec.rb
Labels: enhancement

#1774 Fix/ruby 2793 govpay back office
  Gemfile.lock
  app/services/govpay_refund_details_service.rb
  app/services/govpay_refund_service.rb
  spec/services/govpay_refund_details_service_spec.rb
  spec/services/govpay_refund_service_spec.rb
Labels: bug

#1775 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1786 Feature/ruby 2762 account email
  Gemfile.lock
  app/models/external_user.rb
  app/models/reports/boxi/registrations_serializer.rb
  app/presenters/base_registration_presenter.rb
  app/services/search_email_service.rb
  app/views/shared/registrations/_company_details_panel.html.erb
  config/environments/development.rb
  config/locales/users.en.yml
  lib/tasks/connection.rake
  lib/tasks/lookups.rake
  lib/tasks/notify.rake
  lib/tasks/one_off/clear_lower_tier_with_conviction_flags.rake
  lib/tasks/one_off/create_registration_indices.rake
  lib/tasks/summary_stats.rake
  spec/factories/external_user.rb
  spec/factories/registration.rb
  spec/models/external_user_spec.rb
  spec/models/reports/boxi/registrations_serializer_spec.rb
  spec/requests/routes_spec.rb
  spec/services/search_email_service_spec.rb
  spec/support/fixtures/expire_set_registration_seed.json
  spec/support/fixtures/lower_tier_registration_seed.json
  spec/support/fixtures/registration_seed.json
Labels: housekeeping
