Repository DEFRA/waste-carriers-back-office, pull requests merged in 2024-04, with the labels that each got.

#1897 Feature/ruby 2973 unsubscribe
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile.lock
  app/controllers/cease_or_revoke_forms_controller.rb
  app/controllers/copy_cards_forms_controller.rb
  app/controllers/edit_forms_controller.rb
  app/controllers/payment_method_confirmation_forms_controller.rb
  app/controllers/payment_summary_forms_controller.rb
  app/controllers/registration_completed_forms_controller.rb
  app/controllers/registration_received_pending_conviction_forms_controller.rb
  app/controllers/renewal_complete_forms_controller.rb
  app/controllers/renewal_received_pending_conviction_forms_controller.rb
  app/controllers/user_invitations_controller.rb
  app/helpers/users_helper.rb
  app/models/ability.rb
  app/models/reports/card_orders_export_serializer.rb
  app/presenters/reports/finance_report_presenter.rb
  app/services/clear_nccc_contact_emails_service.rb
  app/services/first_renewal_reminder_service.rb
  app/services/notify/renewal_reminder_email_service.rb
  app/services/renewal_reminder_service_base.rb
  app/services/reports/defra_quarterly_stats_service.rb
  app/services/reports/generate_boxi_files_service.rb
  app/services/second_renewal_reminder_service.rb
  app/services/transient_registration_cleanup_service.rb
  config/initializers/secure_headers.rb
  lib/tasks/one_off/create_unsubscribe_token_index.rake
  lib/tasks/one_off/map_user_journey_types_to_transient_registration_classes.rake
  lib/tasks/one_off/rename_import_conviction_data_role.rake
  lib/tasks/summary_stats.rake
  spec/forms/conviction_reason_form_spec.rb
  spec/lib/tasks/create_unsubscribe_token_index_spec.rb
  spec/lib/tasks/embed_page_views_in_user_journey_spec.rb
  spec/lib/tasks/summary_stats_for_date_range_spec.rb
  spec/models/deregistration_email_export_serializer_spec.rb
  spec/models/reports/card_orders_export_serializer_spec.rb
  spec/models/waste_carriers_engine/registration_spec.rb
  spec/presenters/refund_presenter_spec.rb
  spec/presenters/reminder_letter_presenter_spec.rb
  spec/requests/bank_transfer_payment_forms_spec.rb
  spec/requests/cash_payment_forms_spec.rb
  spec/requests/cheque_payment_forms_spec.rb
  spec/requests/conviction_approval_forms_spec.rb
  spec/requests/download_finance_reports_spec.rb
  spec/requests/postal_order_payment_forms_spec.rb
  spec/services/base_search_service_spec.rb
  spec/services/notify/ad_renewal_letter_service_spec.rb
  spec/services/notify/copy_cards_awaiting_payment_email_service_spec.rb
  spec/services/notify/copy_cards_order_completed_email_service_spec.rb
  spec/services/notify/digital_renewal_letter_service_spec.rb
  spec/services/notify/renewal_reminder_email_service_spec.rb
  spec/services/renewal_reminder_service_base_spec.rb
  spec/services/reports/finance_reports_aws_service_spec.rb
  spec/services/reports/finance_reports_service_spec.rb
  spec/support/shared_examples/rake.rb
Labels: enhancement

#1901 Feature/ruby 2973 unsubscribe
  .github/workflows/ci.yml
  Gemfile.lock
  app/controllers/concerns/can_fetch_resource.rb
  config/mongoid.yml
  spec/services/waste_carriers_engine/unsubscribe_link_service_spec.rb
Labels: bug

#1905 Feature/ruby 2973 unsubscribe
  app/services/notify/renewal_reminder_email_service.rb
  spec/cassettes/notify_renewal_reminder_sends_an_email.yml
  spec/cassettes/notify_resend_renew_email_when_registration_has_contact_email.yml
  spec/services/notify/renewal_reminder_email_service_spec.rb
  spec/spec_helper.rb
Labels: bug

#1913 RUBY-3023 clearing invalid conviction signoffs for transient registrations
  lib/tasks/one_off/clear_invalid_conviction_signoffs.rake
  spec/lib/tasks/clear_invalid_conviction_signoffs_spec.rb
Labels: bug

#1920 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1925 fix/RUBY-3074_edit_bank_transfer_form_back
  Gemfile.lock
  app/views/copy_cards_payment_forms copy/new.html.erb
  app/views/edit_bank_transfer_forms/new.html.erb
Labels: bug

#1926 Fix/ruby 3082 convictions queue missing regs
  lib/tasks/one_off/fix_missing_conviction_signoffs.rake
  spec/lib/tasks/export_copy_card_orders_date_range_spec.rb
  spec/lib/tasks/export_copy_card_orders_spec.rb
  spec/lib/tasks/export_roles_permissions_csv_spec.rb
  spec/lib/tasks/generate_finance_reports_spec.rb
  spec/lib/tasks/lookups_spec.rb
  spec/lib/tasks/notify_spec.rb
  spec/lib/tasks/one_off/clear_area_not_found_values_spec.rb
  spec/lib/tasks/one_off/clear_duplicate_page_views_spec.rb
  spec/lib/tasks/one_off/clear_invalid_conviction_signoffs_spec.rb
  spec/lib/tasks/one_off/clear_lower_tier_with_conviction_flags_spec.rb
  spec/lib/tasks/one_off/clear_nccc_contact_emails_spec.rb
  spec/lib/tasks/one_off/create_unsubscribe_token_index_spec.rb
  spec/lib/tasks/one_off/embed_page_views_in_user_journey_spec.rb
  spec/lib/tasks/one_off/fix_missing_conviction_signoffs_spec.rb
  spec/lib/tasks/one_off/fix_transient_registrations_with_obsolete_fields_spec.rb
  spec/lib/tasks/one_off/map_user_journey_types_to_transient_registration_classes_spec.rb
  spec/lib/tasks/one_off/rename_import_conviction_data_role_spec.rb
  spec/lib/tasks/summary_stats_for_date_range_spec.rb
  spec/support/rake_env.rb
Labels: bug
