Repository DEFRA/waste-carriers-back-office, pull requests merged in 2024-01, with the labels that each got.

#1815 [RUBY-2779] Changing password confirmation error message
  config/locales/users.en.yml
Labels: bug

#1831 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1833 [RUBY-2903] rake task to remove accountEmail field from transient registrations
  lib/tasks/one_off/fix_transient_registrations_with_account_emails.rake
  spec/lib/tasks/fix_transient_registrations_with_account_emails_spec.rb
Labels: bug

#1834 [RUBY-2903] minor adjustments to rake task output
  lib/tasks/one_off/fix_transient_registrations_with_account_emails.rake
  spec/lib/tasks/fix_transient_registrations_with_account_emails_spec.rb
Labels: bug

#1835 Fix/ruby 2903 rake task to remove obsolete fields
  lib/tasks/one_off/fix_transient_registrations_with_account_emails.rake
  lib/tasks/one_off/fix_transient_registrations_with_obsolete_fields.rake
  spec/lib/tasks/fix_transient_registrations_with_obsolete_fields_spec.rb
Labels: bug

#1828 Feature/ruby 2799 user journey ends
  .rubocop.yml
  Gemfile.lock
  app/controllers/analytics_controller.rb
  app/controllers/concerns/waste_carriers_engine/can_redirect_form_to_correct_path.rb
  app/controllers/edit_forms_controller.rb
  app/helpers/transient_payments_helper.rb
  app/presenters/ad_privacy_policy_presenter.rb
  app/presenters/reports/card_order_presenter.rb
  app/services/analytics/aggregated_analytics_service.rb
  app/views/analytics/index.html.erb
  app/views/dashboards/index.html.erb
  app/views/shared/registrations/_expired_panel.html.erb
  config/locales/analytic.en.yml
  config/locales/analytics.en.yml
  config/schedule.rb
  lib/tasks/one_off/clear_area_not_found_values.rake
  lib/tasks/one_off/embed_page_views_in_user_journey.rake
  lib/tasks/one_off/map_user_journey_types_to_transient_registration_classes.rake
  spec/factories/user_journey.rb
  spec/lib/tasks/clear_area_not_found_values_spec.rb
  spec/lib/tasks/embed_page_views_in_user_journey_spec.rb
  spec/lib/tasks/export_copy_card_orders_spec.rb
  spec/lib/tasks/lookups_spec.rb
  spec/lib/tasks/map_user_journey_types_to_transient_registration_classes_spec.rb
  spec/models/deregistration_email_export_serializer_spec.rb
  spec/models/edit_registration_workflow/edit_form_spec.rb
  spec/services/analytics/aggregated_analytics_service_spec.rb
  spec/support/shared_examples/a_manual_address_transition.rb
  spec/support/shared_examples/a_postcode_transition.rb
  spec/support/shared_examples/an_address_lookup_transition.rb
  spec/support/shared_examples/can_create_communication_record.rb
Labels: enhancement
