Repository DEFRA/waste-carriers-back-office, pull requests merged in 2024-06, with the labels that each got.

#1965 Feature/ruby 2859 wcr ensure that scheduled job start and completion events are being recorded in logs
  bin/rake_and_format
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#1970 [RUBY-3222] feat: Add rake task to fix communications_opted_in
  lib/tasks/one_off/create_communications_opted_in_index.rake
  lib/tasks/one_off/fix_communications_opted_in.rake
  spec/lib/tasks/one_off/create_communications_opted_in_index_spec.rb
  spec/lib/tasks/one_off/fix_communications_opted_in_spec.rb
Labels: bug

#1972 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping
